### PR TITLE
Update xsstrike

### PR DESCRIPTION
**Pull request by ha3ke4**
your code have error on line 101

missing parentheses in call to print

### CODE REVIEW

**Comment by arbazkiraak** [comment]
which Python version do you use ?

**Comment by ha3ke4** [comment]
python 3

**Comment by arbazkiraak** [comment]
Tools is based on python2* Versions

**Comment by ha3ke4** [comment]
but when i run the code it shows the error in line 101

**Comment by UltimateHackers** [comment]
Try running it with python2.7 and let me know if the problem exists.

**Comment by ha3ke4** [comment]
it causes error when i run it in termux

**Comment by UltimateHackers** [comment]
Termux isn't a python interpreter.
Looks like Python3 is installed in your termux so all you can do is to install python2 and try running it with the command
`python2 xsstrike`

**Pull request closed without merging**
