### PR TITLE
Create Dockerfile

### PR DESCRIPTION
**Pull request by random-robbie**
Docker version of XSStrike.

Auto updates on build.

### CODE REVIEW

**Comment by UltimateHackers** [comment]
I don't really have much experience with docker files.
If you can write can add a section to the readme about it, that would be great and I will merge the request.
Thanks.

**Comment by random-robbie** [comment]
```
cd XSStike
docker build -t xsstrike .
docker run  -it xsstrike:latest
```

this will build the container and then last bit will let them run xsstrike inside the container :)

**Comment by UltimateHackers** [comment]
As I said earlier, I don't know what that does.
Why would I add that?

**Comment by random-robbie** [comment]
it's like having a virtual machine just for XSStrike.

Handy if someone is complaining they are struggling to install it.

fire up a docker container and they are sorted.

**Comment by arbazkiraak** [comment]
Good idea @random-robbie , Just 37 Mb :) Not bad .

https://hub.docker.com/r/txt3rob/xsstrike-docker/tags/

**Comment by ha3ke4** [comment]
Okk

**Pull request closed without merging**
