### PR TITLE
more readable code

### PR DESCRIPTION
**Pull request by omergunal**
removed old arrays and added new arrays. payloads getting from txt files

### CODE REVIEW

**Comment by UltimateHackers** [comment]
Thanks for contributing in development of XSStrike. I really appreciate your effort.
But looks like your fork is a lil bit buggy. Here's a screenshot of XSStrike and your fork.

**Comment by omergunal** [comment]
i fixed it. can you try again?

**Comment by UltimateHackers** [comment]
Yeah its working now. Good job.

**Comment by UltimateHackers** [comment]
I had set the encoding to UTF-8 manually and its working fine now.

**Comment by UltimateHackers** [comment]
Sorry to say but some payloads are not compatible with the Unicode encoding you have set manually. I have to revert the changes.

**Comment by omergunal** [comment]
Ok, if you will give me payloads i can check it

**Comment by UltimateHackers** [comment]
Payloads were the same sir, but I got an UnicodeDecodeError while testing your fork. I really liked your idea of keeping the payloads separate so people can easily add their payload lists and the code becomes more compact but I can't risk to implant it if can't decode several characters used to obfuscate XSS payloads.

**Pull request merged**
